### PR TITLE
Player join screen Closes #14

### LINKED ISSUE #14: Add player join screen
Up to four players must be able to join the game and choose a colour for their character (RGB sliders?)

### PR DESCRIPTION
**Pull request by ogoding**
This should work, but needs to be checked by someone else to make doubly sure that I didn't accidentally break something when merging in origin/master at the end.

### CODE REVIEW

**Comment by miracle7** [comment]
I pulled this branch, but was unable to build the .dll

Can you commit the .dll if you are able to compile it?

**Comment by ogoding** [comment]
It builds without issue on my machine. What is the error for you? I'll commit the dll in Binaries/Win64/ and hopefully it picks that up.

**Comment by ogoding** [comment]
built .dll file now pushed

**Comment by ogoding** [comment]
This all good to merge? I'll do the controller support in a separate branch

**Pull request merged**
